"""Switch to using string instead of varchar

Revision ID: 79d0e79611d0
Revises: 6c2cab4ba69b
Create Date: 2019-03-26 22:32:43.081552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d0e79611d0'
down_revision = '6c2cab4ba69b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('choices', 'text',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('questions', 'text',
               existing_type=sa.VARCHAR(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('quizzes', 'title',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'title',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.alter_column('questions', 'text',
               existing_type=sa.String(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('choices', 'text',
               existing_type=sa.String(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
